/**
 * The action catalogue.
 *
 * One reusable structure, one entry per action, listing every situation it can
 * be attempted in. Nothing here is ever filtered out for being unlikely: if a
 * player can conceivably try it, it appears on the list with its real number
 * next to it. The rabona is on the same menu as the sideways pass.
 */

import type { ActionIntent, MatchAction, SituationId } from '../types';

export const ACTIONS: MatchAction[] = [
  /* ------------------------------------------------------------ attacking */
  {
    id: 'short-pass',
    name: 'Short Pass',
    category: 'pass',
    situations: ['build-up', 'counter-attack', 'final-third'],
    baseProbability: 84,
    attributeWeights: { passing: 3, technique: 1, composure: 1 },
    opposedBy: { midfield: 1 },
    riskLevel: 'safe',
    intent: { kind: 'retain' },
    blurb: 'Keep the ball moving. Nothing gained, nothing lost.',
    suits: { passing: 'short' },
  },
  {
    id: 'pass-wide',
    name: 'Pass Wide',
    category: 'pass',
    situations: ['build-up', 'counter-attack'],
    baseProbability: 78,
    attributeWeights: { passing: 3, vision: 1 },
    opposedBy: { midfield: 1 },
    riskLevel: 'safe',
    intent: { kind: 'advance', next: 'wing-attack' },
    blurb: 'Find the winger and stretch them.',
  },
  {
    id: 'switch-play',
    name: 'Switch Play',
    category: 'pass',
    situations: ['build-up'],
    baseProbability: 55,
    attributeWeights: { passing: 3, vision: 2, technique: 1 },
    opposedBy: { midfield: 1 },
    riskLevel: 'balanced',
    intent: { kind: 'advance', next: 'wing-attack' },
    blurb: 'Cross-field ball to the far side. Big reward if it lands.',
    suits: { passing: 'direct' },
  },
  {
    id: 'long-pass',
    name: 'Long Pass',
    category: 'pass',
    situations: ['build-up', 'counter-attack'],
    baseProbability: 48,
    attributeWeights: { passing: 3, vision: 2, technique: 1 },
    opposedBy: { midfield: 1, defence: 1 },
    riskLevel: 'balanced',
    intent: { kind: 'advance', next: 'final-third' },
    blurb: 'Skip the midfield entirely.',
    suits: { passing: 'direct', tempo: 'fast' },
  },
  {
    id: 'carry-ball',
    name: 'Carry Ball',
    category: 'dribble',
    situations: ['build-up', 'counter-attack'],
    baseProbability: 50,
    attributeWeights: { pace: 2, technique: 2, flair: 1 },
    opposedBy: { midfield: 2 },
    riskLevel: 'balanced',
    intent: { kind: 'advance', next: 'final-third' },
    blurb: 'Drive at them and commit a defender.',
    suits: { tempo: 'fast' },
  },
  {
    id: 'slow-it-down',
    name: 'Slow It Down',
    category: 'keep',
    situations: ['counter-attack'],
    baseProbability: 88,
    attributeWeights: { composure: 2, technique: 1 },
    opposedBy: { midfield: 1 },
    riskLevel: 'safe',
    intent: { kind: 'retain', next: 'build-up' },
    blurb: 'Kill the counter, keep the ball, take the sting out.',
    suits: { tempo: 'slow', mentality: 'defensive' },
  },
  {
    id: 'through-ball',
    name: 'Through Ball',
    category: 'pass',
    situations: ['build-up', 'counter-attack', 'final-third'],
    baseProbability: 46,
    attributeWeights: { passing: 3, vision: 3, technique: 2 },
    opposedBy: { defence: 2, midfield: 1 },
    riskLevel: 'risky',
    intent: { kind: 'advance', next: 'one-on-one' },
    blurb: 'Split the centre-back and the full-back.',
    suits: { mentality: 'attacking' },
  },
  {
    id: 'difficult-through-ball',
    name: 'Disguised Through Ball',
    category: 'pass',
    situations: ['counter-attack', 'final-third'],
    baseProbability: 14,
    attributeWeights: { vision: 2, technique: 2, flair: 1 },
    opposedBy: { defence: 2 },
    riskLevel: 'risky',
    intent: { kind: 'advance', next: 'one-on-one' },
    blurb: 'No backlift, no look. If it lands, they are gone.',
  },
  {
    id: 'forty-yard-pass',
    name: '40-Yard Pass',
    category: 'pass',
    situations: ['build-up'],
    baseProbability: 4,
    attributeWeights: { passing: 3, vision: 3, technique: 2 },
    opposedBy: { defence: 2 },
    riskLevel: 'extreme',
    intent: { kind: 'advance', next: 'one-on-one' },
    blurb: 'Raking diagonal over the top, first time.',
    suits: { passing: 'direct' },
  },
  {
    id: 'outside-of-the-boot',
    name: 'Outside Of The Boot',
    category: 'pass',
    situations: ['build-up', 'final-third'],
    baseProbability: 2,
    attributeWeights: { flair: 2, technique: 2, vision: 1 },
    opposedBy: { midfield: 1 },
    riskLevel: 'extreme',
    intent: { kind: 'advance', next: 'final-third' },
    intentBySituation: {
      'final-third': { kind: 'advance', next: 'box-chance' },
    },
    blurb: 'Bend it round the defender with the outside of the foot.',
  },
  {
    id: 'long-shot',
    name: 'Long Shot',
    category: 'shot',
    situations: ['build-up', 'counter-attack'],
    baseProbability: 10,
    attributeWeights: { shooting: 3, technique: 2, composure: 1 },
    opposedBy: { goalkeeper: 2, defence: 1 },
    riskLevel: 'risky',
    intent: { kind: 'shot' },
    blurb: 'Thirty yards out. Why not.',
    suits: { mentality: 'very-attacking' },
  },

  /* ---------------------------------------------------------- final third */
  {
    id: 'cross',
    name: 'Cross',
    category: 'cross',
    situations: ['final-third', 'wing-attack'],
    baseProbability: 42,
    attributeWeights: { passing: 2, technique: 2, vision: 1 },
    opposedBy: { defence: 2 },
    riskLevel: 'balanced',
    intent: { kind: 'advance', next: 'box-chance' },
    blurb: 'Put it in the mixer.',
    suits: { passing: 'direct' },
  },
  {
    id: 'dribble',
    name: 'Dribble',
    category: 'dribble',
    situations: ['final-third', 'wing-attack'],
    baseProbability: 30,
    attributeWeights: { pace: 3, technique: 2, flair: 1 },
    opposedBy: { defence: 3 },
    riskLevel: 'risky',
    intent: { kind: 'advance', next: 'box-chance' },
    blurb: 'Take the defender on and go past them.',
  },
  {
    id: 'shoot',
    name: 'Shoot',
    category: 'shot',
    situations: ['final-third'],
    baseProbability: 24,
    attributeWeights: { shooting: 3, technique: 2, composure: 1 },
    opposedBy: { goalkeeper: 2, defence: 1 },
    riskLevel: 'risky',
    intent: { kind: 'shot' },
    blurb: 'Have a go from the edge of the area.',
  },
  {
    id: 'layoff',
    name: 'Layoff',
    category: 'pass',
    situations: ['final-third', 'box-chance'],
    baseProbability: 80,
    attributeWeights: { technique: 2, composure: 2, passing: 1 },
    opposedBy: { defence: 1 },
    riskLevel: 'safe',
    intent: { kind: 'retain', next: 'final-third' },
    blurb: 'Set it back to the runner and let someone else decide.',
    suits: { passing: 'short' },
  },

  /* --------------------------------------------------------- wing attacks */
  {
    id: 'low-cross',
    name: 'Low Cross',
    category: 'cross',
    situations: ['wing-attack'],
    baseProbability: 36,
    attributeWeights: { passing: 3, technique: 2 },
    opposedBy: { defence: 2 },
    riskLevel: 'balanced',
    intent: { kind: 'advance', next: 'box-chance' },
    blurb: 'Drilled across the face of goal. Hard to defend, hard to hit.',
  },
  {
    id: 'long-cross',
    name: 'Long Cross',
    category: 'cross',
    situations: ['wing-attack'],
    baseProbability: 32,
    attributeWeights: { passing: 2, strength: 1, vision: 1 },
    opposedBy: { defence: 1, goalkeeper: 1 },
    riskLevel: 'balanced',
    intent: { kind: 'advance', next: 'box-chance' },
    blurb: 'Hang it up to the back post.',
  },
  {
    id: 'cut-inside',
    name: 'Cut Inside',
    category: 'dribble',
    situations: ['wing-attack'],
    baseProbability: 44,
    attributeWeights: { technique: 2, pace: 2, flair: 1 },
    opposedBy: { defence: 2 },
    riskLevel: 'balanced',
    intent: { kind: 'advance', next: 'final-third' },
    blurb: 'Come off the line onto your stronger foot.',
  },
  {
    id: 'pass-back',
    name: 'Pass Back',
    category: 'keep',
    situations: ['wing-attack'],
    baseProbability: 86,
    attributeWeights: { passing: 2, composure: 1 },
    opposedBy: { attack: 1 },
    riskLevel: 'safe',
    intent: { kind: 'retain', next: 'build-up' },
    blurb: 'Recycle it and start again.',
    suits: { passing: 'short', tempo: 'slow' },
  },
  {
    id: 'rabona',
    name: 'Rabona',
    category: 'cross',
    situations: ['wing-attack'],
    baseProbability: 1,
    attributeWeights: { flair: 2, technique: 2 },
    opposedBy: { defence: 1 },
    riskLevel: 'extreme',
    intent: { kind: 'advance', next: 'box-chance' },
    blurb: 'Wrong foot, wrong side, whipped in behind the standing leg.',
  },
  {
    id: 'backheel',
    name: 'Backheel',
    category: 'pass',
    situations: ['wing-attack', 'final-third'],
    baseProbability: 3,
    attributeWeights: { flair: 2, technique: 2 },
    opposedBy: { defence: 1 },
    riskLevel: 'extreme',
    intent: { kind: 'advance', next: 'box-chance' },
    blurb: 'Cheeky flick round the corner into the run.',
  },

  /* ---------------------------------------------------------- box chances */
  {
    id: 'first-time-shot',
    name: 'First-Time Shot',
    category: 'shot',
    situations: ['box-chance'],
    baseProbability: 32,
    attributeWeights: { shooting: 3, technique: 2, composure: 1 },
    opposedBy: { goalkeeper: 2, defence: 1 },
    riskLevel: 'risky',
    intent: { kind: 'shot' },
    blurb: 'Hit it before the defence can set.',
    suits: { tempo: 'fast' },
  },
  {
    id: 'header',
    name: 'Header',
    category: 'shot',
    situations: ['box-chance'],
    baseProbability: 30,
    attributeWeights: { strength: 2, positioning: 2, shooting: 1 },
    opposedBy: { goalkeeper: 2, defence: 1 },
    riskLevel: 'risky',
    intent: { kind: 'shot' },
    blurb: 'Attack the ball and put your head on it.',
  },
  {
    id: 'control-and-shoot',
    name: 'Control And Shoot',
    category: 'shot',
    situations: ['box-chance'],
    baseProbability: 28,
    attributeWeights: { technique: 3, composure: 2, shooting: 2 },
    opposedBy: { goalkeeper: 1, defence: 3 },
    riskLevel: 'risky',
    intent: { kind: 'shot' },
    blurb: 'Take a touch. Better contact, but they get a body in the way.',
    suits: { tempo: 'slow' },
  },
  {
    id: 'volley',
    name: 'First-Time Volley',
    category: 'shot',
    situations: ['box-chance'],
    baseProbability: 8,
    attributeWeights: { technique: 3, shooting: 2, composure: 1 },
    opposedBy: { goalkeeper: 1 },
    riskLevel: 'extreme',
    intent: { kind: 'shot' },
    blurb: 'Meet it on the drop, laces through it.',
  },
  {
    id: 'bicycle-kick',
    name: 'Bicycle Kick',
    category: 'shot',
    situations: ['box-chance'],
    baseProbability: 1,
    attributeWeights: { flair: 2, technique: 2, shooting: 1 },
    opposedBy: { goalkeeper: 1 },
    riskLevel: 'extreme',
    intent: { kind: 'shot' },
    blurb: 'Back to goal. Off the floor. Absolute nonsense.',
  },
  {
    id: 'backheel-finish',
    name: 'Backheel Finish',
    category: 'shot',
    situations: ['box-chance'],
    baseProbability: 2,
    attributeWeights: { flair: 2, technique: 2 },
    opposedBy: { goalkeeper: 1 },
    riskLevel: 'extreme',
    intent: { kind: 'shot' },
    blurb: 'Flick it back across the keeper without breaking stride.',
  },

  /* ---------------------------------------------------------- one on ones */
  {
    id: 'shoot-one-on-one',
    name: 'Shoot',
    category: 'shot',
    situations: ['one-on-one'],
    baseProbability: 58,
    attributeWeights: { shooting: 3, composure: 2, technique: 1 },
    opposedBy: { goalkeeper: 3 },
    riskLevel: 'balanced',
    intent: { kind: 'shot' },
    blurb: 'Pick your spot and hit it.',
  },
  {
    id: 'place-shot',
    name: 'Place Shot',
    category: 'shot',
    situations: ['one-on-one'],
    baseProbability: 54,
    attributeWeights: { composure: 3, technique: 2, shooting: 1 },
    opposedBy: { goalkeeper: 3 },
    riskLevel: 'balanced',
    intent: { kind: 'shot' },
    blurb: 'Side-foot it into the corner. No power, all placement.',
    suits: { tempo: 'slow' },
  },
  {
    id: 'power-shot',
    name: 'Power Shot',
    category: 'shot',
    situations: ['one-on-one'],
    baseProbability: 48,
    attributeWeights: { shooting: 4, strength: 1 },
    opposedBy: { goalkeeper: 2 },
    riskLevel: 'balanced',
    intent: { kind: 'shot' },
    blurb: 'Through it. Give the keeper no time.',
    suits: { mentality: 'very-attacking' },
  },
  {
    id: 'pass-across-goal',
    name: 'Pass Across Goal',
    category: 'pass',
    situations: ['one-on-one'],
    baseProbability: 40,
    attributeWeights: { vision: 2, passing: 2, composure: 1 },
    opposedBy: { goalkeeper: 1, defence: 2 },
    riskLevel: 'balanced',
    intent: { kind: 'shot' },
    blurb: 'Square it for the tap-in — if anyone has kept up.',
    suits: { passing: 'short' },
  },
  {
    id: 'round-keeper',
    name: 'Round The Goalkeeper',
    category: 'dribble',
    situations: ['one-on-one'],
    baseProbability: 18,
    attributeWeights: { technique: 3, pace: 2, composure: 1 },
    opposedBy: { goalkeeper: 2 },
    riskLevel: 'risky',
    intent: { kind: 'shot' },
    blurb: 'Take it round them and roll it in.',
  },
  {
    id: 'chip',
    name: 'Chip',
    category: 'shot',
    situations: ['one-on-one'],
    baseProbability: 4,
    attributeWeights: { technique: 2, composure: 1, flair: 1 },
    opposedBy: { goalkeeper: 1 },
    riskLevel: 'extreme',
    intent: { kind: 'shot' },
    blurb: 'Dink it over the diving keeper.',
  },
  {
    id: 'panenka',
    name: 'Panenka',
    category: 'shot',
    situations: ['one-on-one'],
    baseProbability: 1,
    attributeWeights: { flair: 2, composure: 2 },
    opposedBy: { goalkeeper: 1 },
    riskLevel: 'extreme',
    intent: { kind: 'shot' },
    blurb: 'Stop. Wait. Scoop it down the middle. Career-defining either way.',
  },

  /* ------------------------------------------------------------ defending */
  {
    id: 'hold-shape',
    name: 'Hold Shape',
    category: 'defend',
    situations: ['opposition-counter'],
    baseProbability: 78,
    attributeWeights: { positioning: 3, composure: 1 },
    opposedBy: { attack: 1 },
    riskLevel: 'safe',
    intent: { kind: 'delay', next: 'defend-cross' },
    blurb: 'Get bodies back. Concede ground, not chances.',
    suits: { mentality: 'defensive', pressing: 'low' },
  },
  {
    id: 'drop-deep',
    name: 'Drop Deep',
    category: 'defend',
    situations: ['opposition-counter'],
    baseProbability: 74,
    attributeWeights: { positioning: 2, composure: 2 },
    opposedBy: { attack: 1 },
    riskLevel: 'safe',
    intent: { kind: 'delay', next: 'defend-cross' },
    blurb: 'Back off into the block and make them break you down.',
    suits: { mentality: 'defensive' },
  },
  {
    id: 'press-ball-carrier',
    name: 'Press Ball Carrier',
    category: 'defend',
    situations: ['opposition-counter'],
    baseProbability: 40,
    attributeWeights: { defending: 3, pace: 2, strength: 1 },
    opposedBy: { attack: 2, midfield: 1 },
    riskLevel: 'balanced',
    intent: { kind: 'stop' },
    blurb: 'Go and win it back right now.',
    suits: { pressing: 'high' },
  },
  {
    id: 'track-runner',
    name: 'Track Runner',
    category: 'defend',
    situations: ['opposition-counter', 'defend-through-ball'],
    baseProbability: 58,
    attributeWeights: { pace: 3, positioning: 2 },
    opposedBy: { attack: 1 },
    riskLevel: 'balanced',
    intent: { kind: 'delay', next: 'defend-through-ball' },
    intentBySituation: {
      'defend-through-ball': { kind: 'stop' },
    },
    blurb: 'Forget the ball. Go with the runner.',
  },
  {
    id: 'force-wide',
    name: 'Force Wide',
    category: 'defend',
    situations: ['opposition-counter', 'defend-through-ball', 'defend-one-on-one'],
    baseProbability: 56,
    attributeWeights: { positioning: 3, pace: 1 },
    opposedBy: { attack: 1 },
    riskLevel: 'balanced',
    intent: { kind: 'delay', next: 'defend-cross' },
    intentBySituation: {
      'defend-one-on-one': { kind: 'stop' },
    },
    blurb: 'Show them onto the touchline and away from goal.',
  },
  {
    id: 'tactical-foul',
    name: 'Tactical Foul',
    category: 'defend',
    situations: ['opposition-counter'],
    baseProbability: 62,
    attributeWeights: { strength: 2, defending: 1 },
    opposedBy: { attack: 1 },
    riskLevel: 'risky',
    intent: { kind: 'stop' },
    commitsFoul: true,
    blurb: 'Take the booking. Kill the attack.',
  },
  {
    id: 'attempt-interception',
    name: 'Attempt Interception',
    category: 'defend',
    situations: ['opposition-counter', 'defend-through-ball'],
    baseProbability: 24,
    attributeWeights: { positioning: 3, pace: 2, defending: 1 },
    opposedBy: { midfield: 1, attack: 1 },
    riskLevel: 'risky',
    intent: { kind: 'stop' },
    blurb: 'Gamble on the pass. Get it wrong and you are out of the picture.',
    suits: { pressing: 'high' },
  },
  {
    id: 'step-up',
    name: 'Step Up',
    category: 'defend',
    situations: ['defend-through-ball'],
    baseProbability: 26,
    attributeWeights: { positioning: 4, composure: 1 },
    opposedBy: { attack: 2 },
    riskLevel: 'risky',
    intent: { kind: 'stop' },
    blurb: 'Push the line and play them offside. All or nothing.',
    suits: { pressing: 'high', mentality: 'attacking' },
  },
  {
    id: 'close-down',
    name: 'Close Down',
    category: 'defend',
    situations: ['defend-through-ball', 'defend-one-on-one'],
    baseProbability: 52,
    attributeWeights: { pace: 2, defending: 2, positioning: 1 },
    opposedBy: { attack: 2 },
    riskLevel: 'balanced',
    intent: { kind: 'delay', next: 'defend-one-on-one' },
    intentBySituation: {
      'defend-one-on-one': { kind: 'stop' },
    },
    blurb: 'Get tight and narrow the angle.',
    suits: { pressing: 'high' },
  },
  {
    id: 'mark-striker',
    name: 'Mark Striker',
    category: 'defend',
    situations: ['defend-cross'],
    baseProbability: 48,
    attributeWeights: { positioning: 3, strength: 2, defending: 1 },
    opposedBy: { attack: 2 },
    riskLevel: 'balanced',
    intent: { kind: 'stop' },
    blurb: 'Stay side-on and do not let them get across you.',
  },
  {
    id: 'attack-ball',
    name: 'Attack The Ball',
    category: 'defend',
    situations: ['defend-cross'],
    baseProbability: 44,
    attributeWeights: { strength: 3, positioning: 1, pace: 1 },
    opposedBy: { attack: 2 },
    riskLevel: 'balanced',
    intent: { kind: 'stop' },
    blurb: 'Go and meet it. First to the ball wins the header.',
  },
  {
    id: 'defend-near-post',
    name: 'Defend Near Post',
    category: 'defend',
    situations: ['defend-cross'],
    baseProbability: 50,
    attributeWeights: { positioning: 3, pace: 1 },
    opposedBy: { attack: 1 },
    riskLevel: 'balanced',
    intent: { kind: 'stop' },
    blurb: 'Cover the flick-on at the front post.',
  },
  {
    id: 'defend-far-post',
    name: 'Defend Far Post',
    category: 'defend',
    situations: ['defend-cross'],
    baseProbability: 46,
    attributeWeights: { positioning: 2, strength: 2 },
    opposedBy: { attack: 1 },
    riskLevel: 'balanced',
    intent: { kind: 'stop' },
    blurb: 'Sit on the back post and deal with the hanging ball.',
  },
  {
    id: 'clear',
    name: 'Clear',
    category: 'defend',
    situations: ['defend-cross'],
    baseProbability: 54,
    attributeWeights: { defending: 3, strength: 1 },
    opposedBy: { attack: 1 },
    riskLevel: 'balanced',
    intent: { kind: 'stop' },
    blurb: 'Row Z. No arguments.',
  },
  {
    id: 'stand-off',
    name: 'Stand Off',
    category: 'defend',
    situations: ['defend-one-on-one'],
    baseProbability: 60,
    attributeWeights: { positioning: 3, composure: 2 },
    opposedBy: { attack: 2 },
    riskLevel: 'balanced',
    intent: { kind: 'delay', next: 'defend-cross' },
    blurb: 'Do not dive in. Buy time for the cavalry.',
    suits: { pressing: 'low' },
  },
  {
    id: 'tackle',
    name: 'Tackle',
    category: 'defend',
    situations: ['defend-one-on-one'],
    baseProbability: 34,
    attributeWeights: { defending: 4, strength: 1, composure: 1 },
    opposedBy: { attack: 2 },
    riskLevel: 'risky',
    intent: { kind: 'stop' },
    blurb: 'Go in and take the ball.',
  },
  {
    id: 'risk-challenge',
    name: 'Risk Everything',
    category: 'defend',
    situations: ['defend-one-on-one'],
    baseProbability: 10,
    attributeWeights: { defending: 2, strength: 2, pace: 1 },
    opposedBy: { attack: 1 },
    riskLevel: 'extreme',
    intent: { kind: 'stop' },
    blurb: 'Full-blooded, both feet off the ground, heart over head.',
  },
  {
    id: 'last-ditch-block',
    name: 'Last-Ditch Block',
    category: 'defend',
    situations: ['defend-one-on-one'],
    baseProbability: 6,
    attributeWeights: { positioning: 2, strength: 1, pace: 2 },
    opposedBy: { attack: 1 },
    riskLevel: 'extreme',
    intent: { kind: 'stop' },
    blurb: 'Throw yourself in front of it and hope.',
  },
];

const BY_ID = new Map(ACTIONS.map((action) => [action.id, action]));

export function getAction(id: string): MatchAction {
  const action = BY_ID.get(id);
  if (!action) throw new Error(`Unknown action: ${id}`);
  return action;
}

export function getActionsForSituation(situation: SituationId): MatchAction[] {
  return ACTIONS.filter((action) => action.situations.includes(situation));
}

/** The intent for this action *in this situation*, honouring any override. */
export function intentFor(action: MatchAction, situation: SituationId): ActionIntent {
  return action.intentBySituation?.[situation] ?? action.intent;
}

export const RISK_LABELS: Record<MatchAction['riskLevel'], string> = {
  safe: 'SAFE',
  balanced: 'BALANCED',
  risky: 'RISKY',
  extreme: 'EXTREME',
};
